MetaArguments:
  log_file_path: "tgrag_gnn.log"
  global_seed: 42

ExperimentArguments:
  exp_args:
    GCN_RNI:
      model_args:
        model: "GCN"
        encoder: "RNI"
        encoder_col: "random"
        num_layers: 3
        hidden_channels: 128
        dropout: 0.5
        lr: 0.01
        epochs: 100
        runs: 5
        device: 0
        log_steps: 10
      data_args:
        task_name: "node-regression"
        is_regression: true
        node_file: "temporal_nodes.csv"
        edge_file: "temporal_edges.csv"
        is_scratch_location: false
        num_test_shards: 2
    SAGE_RNI:
      model_args:
        model: "SAGE"
        encoder: "RNI"
        encoder_col: "random"
        num_layers: 3
        hidden_channels: 128
        dropout: 0.5
        lr: 0.01
        epochs: 100
        runs: 5
        device: 0
        log_steps: 10
      data_args:
        task_name: "node-regression"
        is_regression: true
        node_file: "temporal_nodes.csv"
        edge_file: "temporal_edges.csv"
        is_scratch_location: false
        num_test_shards: 2
    GAT_RNI:
      model_args:
        model: "GAT"
        encoder: "RNI"
        encoder_col: "random"
        num_layers: 3
        hidden_channels: 64
        dropout: 0.5
        lr: 0.01
        epochs: 100
        runs: 5
        device: 0
        log_steps: 10
      data_args:
        task_name: "node-regression"
        is_regression: true
        node_file: "temporal_nodes.csv"
        edge_file: "temporal_edges.csv"
        is_scratch_location: false
        num_test_shards: 2
