MetaArguments:
  log_file_path: "tgrag_gnn.log"
  node_file: "data/crawl-data/temporal/temporal_nodes.csv"
  edge_file: "data/crawl-data/temporal/temporal_edges.csv"
  is_scratch_location: false
  global_seed: 42

ExperimentArguments:
  exp_args:
    GCN_RNI:
      model_args:
        model: "GCN"
        num_layers: 3
        hidden_channels: 128
        batch_size: 128
        dropout: 0.5
        lr: 0.01
        epochs: 100
        runs: 1
        device: 0
        log_steps: 10
      data_args:
        task_name: "node-regression"
        is_regression: true
        num_test_shards: 2
    SAGE_RNI:
      model_args:
        model: "SAGE"
        num_layers: 3
        hidden_channels: 128
        batch_size: 128
        dropout: 0.5
        lr: 0.01
        epochs: 100
        runs: 1
        device: 0
        log_steps: 10
      data_args:
        task_name: "node-regression"
        is_regression: true
        num_test_shards: 2
    GAT_RNI:
      model_args:
        model: "GAT"
        num_layers: 3
        hidden_channels: 64
        batch_size: 128
        dropout: 0.5
        lr: 0.01
        epochs: 100
        runs: 1
        device: 0
        log_steps: 10
      data_args:
        task_name: "node-regression"
        is_regression: true
        num_test_shards: 2
