MetaArguments:
  log_file_path: "tgrag_pr_correlation.log"
  global_seed: 42

ExperimentArguments:
  exp_args:
    PRC_BIN:
      model_args:
        model: "bin"
        encoder:
        encoder_col:
        num_layers:
        hidden_channels:
        dropout:
        lr:
        epochs:
        runs:
        device:
        log_steps:
      data_args:
        task_name: "correlation"
        is_regression: true
        node_file: 'data/crawl-data/manual/output/test_pr_cr.csv'
        edge_file: 'data/crawl-data/manual/temporal_edges.csv'
        is_scratch_location: false
        num_test_shards:
    PRC:
      model_args:
        model:
        encoder:
        encoder_col:
        num_layers:
        hidden_channels:
        dropout:
        lr:
        epochs:
        runs:
        device:
        log_steps:
      data_args:
        task_name: "correlation"
        is_regression: true
        node_file: 'data/crawl-data/manual/output/test_pr_cr.csv'
        edge_file: 'data/crawl-data/manual/temporal_edges.csv'
        is_scratch_location: false
        num_test_shards:
